
name: Piepeline for tests
on : [push, workflow_dispatch]
jobs: 
  build-node : 
   runs-on : windows-latest

   steps:
   - run: node --version 
   - run: npm --version  
   - uses: actions/checkout@v4
   - run : npm install 
     name : Install depedencies 
   - run : npm run test
     name : run tests
  